[package]
name = "gwasm-api"
version = "0.1.0"
authors = ["Jakub Konka <jakub.konka@golem.network>"]
edition = "2018"

[dependencies]
actix = "0.8"
failure = "0.1"
futures = "0.1"
actix-wamp = { git = "https://github.com/golemfactory/golem-client" }
golem-rpc-api = { git = "https://github.com/golemfactory/golem-client" }
golem-rpc-macros = { git = "https://github.com/golemfactory/golem-client" }
serde_json = "1"
serde = { version = "1", features = ["derive"] }
chrono = "0.4"
tempfile = "3.0"
tokio-ctrlc-error = "0.1"
tokio = "0.1"
