(function() {var implementors = {};
implementors["gwasm_api"] = [{text:"impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/marker/trait.Send.html\" title=\"trait core::marker::Send\">Send</a> for <a class=\"enum\" href=\"gwasm_api/error/enum.Error.html\" title=\"enum gwasm_api::error::Error\">Error</a>",synthetic:true,types:["gwasm_api::error::Error"]},{text:"impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/marker/trait.Send.html\" title=\"trait core::marker::Send\">Send</a> for <a class=\"struct\" href=\"gwasm_api/task/struct.GWasmBinary.html\" title=\"struct gwasm_api::task::GWasmBinary\">GWasmBinary</a>",synthetic:true,types:["gwasm_api::task::GWasmBinary"]},{text:"impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/marker/trait.Send.html\" title=\"trait core::marker::Send\">Send</a> for <a class=\"struct\" href=\"gwasm_api/task/struct.TaskBuilder.html\" title=\"struct gwasm_api::task::TaskBuilder\">TaskBuilder</a>",synthetic:true,types:["gwasm_api::task::TaskBuilder"]},{text:"impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/marker/trait.Send.html\" title=\"trait core::marker::Send\">Send</a> for <a class=\"struct\" href=\"gwasm_api/task/struct.Task.html\" title=\"struct gwasm_api::task::Task\">Task</a>",synthetic:true,types:["gwasm_api::task::Task"]},{text:"impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/marker/trait.Send.html\" title=\"trait core::marker::Send\">Send</a> for <a class=\"struct\" href=\"gwasm_api/task/struct.Options.html\" title=\"struct gwasm_api::task::Options\">Options</a>",synthetic:true,types:["gwasm_api::task::Options"]},{text:"impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/marker/trait.Send.html\" title=\"trait core::marker::Send\">Send</a> for <a class=\"struct\" href=\"gwasm_api/task/struct.Subtask.html\" title=\"struct gwasm_api::task::Subtask\">Subtask</a>",synthetic:true,types:["gwasm_api::task::Subtask"]},{text:"impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/marker/trait.Send.html\" title=\"trait core::marker::Send\">Send</a> for <a class=\"struct\" href=\"gwasm_api/task/struct.ComputedTask.html\" title=\"struct gwasm_api::task::ComputedTask\">ComputedTask</a>",synthetic:true,types:["gwasm_api::task::ComputedTask"]},{text:"impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/marker/trait.Send.html\" title=\"trait core::marker::Send\">Send</a> for <a class=\"struct\" href=\"gwasm_api/task/struct.ComputedSubtask.html\" title=\"struct gwasm_api::task::ComputedSubtask\">ComputedSubtask</a>",synthetic:true,types:["gwasm_api::task::ComputedSubtask"]},{text:"impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/marker/trait.Send.html\" title=\"trait core::marker::Send\">Send</a> for <a class=\"struct\" href=\"gwasm_api/timeout/struct.Timeout.html\" title=\"struct gwasm_api::timeout::Timeout\">Timeout</a>",synthetic:true,types:["gwasm_api::timeout::Timeout"]},];

            if (window.register_implementors) {
                window.register_implementors(implementors);
            } else {
                window.pending_implementors = implementors;
            }
        
})()
