//! Errors that can be returned by the library
use actix::MailboxError;
use failure::Fail;
use std::io;
use tokio::timer;

/// Enum wrapping all possible errors that can be generated by the library
#[derive(Debug, Fail)]
pub enum Error {
    /// Wraps actix's `MailboxError` error
    #[fail(display = "Actix mailbox error")]
    MailboxError(MailboxError),

    /// Wraps tokio's `timer::Error` error
    #[fail(display = "Tokio timer error")]
    TimerError(timer::Error),

    /// Wraps libstd's `std::io::Error` error
    #[fail(display = "I/O error")]
    IOError(io::Error),

    /// Wraps Golem's `actix_wamp::Error` error
    #[fail(display = "Actix WAMP error")]
    WampError(actix_wamp::Error),

    /// Wraps Golem RPC's `golem_rpc_api::Error` error
    #[fail(display = "Golem RPC error")]
    GolemRPCError(golem_rpc_api::Error),

    /// Wraps `tokio_ctrlc_error::KeyboardInterrupt` which is used to handle
    /// Ctrl-C interrupt event for the lib's client
    #[fail(display = "Keyboard interrupt")]
    KeyboardInterrupt(tokio_ctrlc_error::KeyboardInterrupt),

    /// Wraps other `tokio_ctrlc_error::IoError` type errors
    #[fail(display = "Tokio Ctrl-C error")]
    CtrlcError(tokio_ctrlc_error::IoError),

    /// Wraps `chrono::ParseError` error
    #[fail(display = "Chrono error")]
    ChronoError(chrono::ParseError),

    /// Error generated when trying to create a zero [`Timeout`](../timeout/struct.Timeout.html)
    /// value for a Golem Task
    #[fail(display = "Zero timeout error")]
    ZeroTimeoutError,
}

impl From<io::Error> for Error {
    fn from(err: io::Error) -> Self {
        Error::IOError(err)
    }
}

impl From<MailboxError> for Error {
    fn from(err: MailboxError) -> Self {
        Error::MailboxError(err)
    }
}

impl From<timer::Error> for Error {
    fn from(err: timer::Error) -> Self {
        Error::TimerError(err)
    }
}

impl From<actix_wamp::Error> for Error {
    fn from(err: actix_wamp::Error) -> Self {
        Error::WampError(err)
    }
}

impl From<golem_rpc_api::Error> for Error {
    fn from(err: golem_rpc_api::Error) -> Self {
        Error::GolemRPCError(err)
    }
}

impl From<tokio_ctrlc_error::IoError> for Error {
    fn from(err: tokio_ctrlc_error::IoError) -> Self {
        Error::CtrlcError(err)
    }
}

impl From<tokio_ctrlc_error::KeyboardInterrupt> for Error {
    fn from(err: tokio_ctrlc_error::KeyboardInterrupt) -> Self {
        Error::KeyboardInterrupt(err)
    }
}

impl From<chrono::ParseError> for Error {
    fn from(err: chrono::ParseError) -> Self {
        Error::ChronoError(err)
    }
}
